let numero1 = 25;
let numero2 = 23;
let suma = numero1 + numero2; 
let resta = numero1 - numero2; 
let multiplicacion = numero1 * numero2; 
let division = numero1 / numero2;
alert(suma);
alert(resta);
alert(multiplicacion);
alert(division);
